[project]
name = "dbt-electrostore"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-postgres>=1.9.1",
    "dbt-sqlserver>=1.9.0",
]
